import { useEffect, useState, type ReactNode } from 'react';
import { Link, useRouterState } from '@tanstack/react-router';
import { Moon, Sun, Menu, X, ArrowUp, ArrowUpRight, Heart } from 'lucide-react';
import { Toaster } from 'sonner';
import { Button } from '@/components/ui/button';
import { navigation, profile, pageDescriptions } from '@/data/portfolio';
import { SocialLinks } from './shared';
export function PortfolioLayout({children}:{children:ReactNode}) {
 const path=useRouterState({select:s=>s.location.pathname});const home=path==='/';
 const [menu,setMenu]=useState(false);const [scrolled,setScrolled]=useState(false);const [active,setActive]=useState('home');const [light,setLight]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem('portfolio-theme');const isLight=saved==='light';setLight(isLight);document.documentElement.dataset.theme=isLight?'light':'dark';},[]);
 useEffect(()=>{setMenu(false);},[path]);
 useEffect(()=>{document.body.style.overflow=menu?'hidden':'';return()=>{document.body.style.overflow='';};},[menu]);
 useEffect(()=>{const onScroll=()=>{setScrolled(window.scrollY>35);const range=document.documentElement.scrollHeight-window.innerHeight;document.documentElement.style.setProperty('--scroll',`${range>0?window.scrollY/range:0}`);if(home){let current='home';for(const n of navigation){const el=document.getElementById(n.id);if(el&&el.getBoundingClientRect().top<=150)current=n.id;}setActive(current);}};onScroll();window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll);},[home]);
 function toggleTheme(){const next=!light;setLight(next);document.documentElement.dataset.theme=next?'light':'dark';localStorage.setItem('portfolio-theme',next?'light':'dark');}
 return <><a href="#main-content" className="sr-only focus:not-sr-only focus:fixed focus:top-5 focus:left-5 focus:z-[90] bg-primary text-primary-foreground p-3">Skip to content</a><div className="boot-mark" aria-hidden="true"><span>am.</span></div><div className="scroll-progress" aria-hidden="true"/><header className={`site-header ${scrolled||!home||menu?'scrolled':''} ${home?'home-header':''}`}><div className="container header-inner"><Link className="brand min-w-0" to="/">alex morgan<span>.</span></Link><nav className="header-nav" aria-label="Main navigation">{navigation.map(n=>home?<a href={`#${n.id}`} key={n.id} className={`nav-link ${active===n.id?'active':''}`} aria-current={active===n.id?'location':undefined}>{n.label}</a>:<Link to={n.to} key={n.id} className="nav-link" activeProps={{className:'nav-link active'}} activeOptions={{exact:true}}>{n.label}</Link>)}</nav><div className="header-tools shrink-0"><Button variant="ghost" size="icon" className="theme-button" aria-label={light?'Switch to dark theme':'Switch to light theme'} title={light?'Dark theme':'Light theme'} onClick={toggleTheme}>{light?<Moon size={16}/>:<Sun size={16}/>}</Button><Button size="sm" className="header-contact" asChild><Link to="/contact">Let’s Talk<ArrowUpRight size={13}/></Link></Button><Button variant="ghost" size="icon" className="mobile-toggle" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="mobile-navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></div></div></header>{menu&&<nav id="mobile-navigation" className="mobile-menu" aria-label="Mobile navigation" onKeyDown={e=>{if(e.key==='Escape')setMenu(false);}}>{navigation.map(n=>home?<a href={`#${n.id}`} key={n.id} onClick={()=>setMenu(false)}>{n.label}</a>:<Link key={n.id} to={n.to} onClick={()=>setMenu(false)}>{n.label}</Link>)}<Link to="/certifications">Certifications</Link><Link to="/achievements">Achievements</Link><Link to="/testimonials">Testimonials</Link></nav>}<main id="main-content" tabIndex={-1}>{children}</main><Footer/>{scrolled&&<Button size="icon" variant="outline" className="back-top" title="Back to top" aria-label="Back to top" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}><ArrowUp size={15}/></Button>}<Toaster position="bottom-right" theme={light?'light':'dark'} richColors/></>;
}
function Footer(){return <footer className="site-footer"><div className="container"><div className="footer-top"><div><Link className="brand" to="/">alex morgan<span>.</span></Link><p>Thoughtful code. Meaningful experiences.<br/>Always curious. Always building.</p></div><nav className="footer-nav" aria-label="Footer navigation"><Link to="/about">About</Link><Link to="/projects">Projects</Link><Link to="/certifications">Certifications</Link><Link to="/achievements">Achievements</Link><Link to="/testimonials">Testimonials</Link><Link to="/contact">Contact</Link></nav><SocialLinks/></div><div className="footer-bottom"><p>© 2026 {profile.name}. All rights reserved.</p><span>Built with care &amp; a little curiosity<Heart size={10} className="text-primary"/></span><p>Fictional portfolio · Sample content</p></div></div></footer>;}
export function PageIntro({page,title}:{page:string;title:string}){return <div className="container page-intro reveal"><div className="eyebrow"><span className="status-dot"/>ALEX MORGAN / {title.toUpperCase()}</div><h1>{title}<span className="text-primary">.</span></h1><p>{pageDescriptions[page]}</p></div>;}
