import { Link } from '@tanstack/react-router';
import { ArrowUpRight, Code2, Cloud, Database, Terminal, Sparkles, PenTool, Layers, Gauge, Github, Linkedin, Instagram, Mail, Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { profile } from '@/data/portfolio';
import { toast } from 'sonner';
export const icons:Record<string,typeof Code2>={code:Code2,cloud:Cloud,database:Database,terminal:Terminal,sparkles:Sparkles,pen:PenTool,layers:Layers,gauge:Gauge};
export function SectionHeading({number,label,title,description,link}:{number:string;label:string;title:string;description?:string;link?:{to:'/projects'|'/about'|'/services'|'/resume';label:string}|undefined}) {return <div className="section-heading"><div><div className="eyebrow"><span className="section-number">{number}</span><span>/</span>{label}</div><h2>{title}</h2>{description&&<p>{description}</p>}</div>{link&&<Link className="text-link" to={link.to}>{link.label}<ArrowUpRight size={15}/></Link>}</div>;}
export function SocialLinks(){return <div className="social-links"><a href="https://github.com" target="_blank" rel="noreferrer" aria-label="GitHub sample link" title="GitHub"><Github size={17}/></a><a href="https://linkedin.com" target="_blank" rel="noreferrer" aria-label="LinkedIn sample link" title="LinkedIn"><Linkedin size={17}/></a><a href={`mailto:${profile.email}`} aria-label="Email Alex" title="Email"><Mail size={17}/></a><a href="https://instagram.com" target="_blank" rel="noreferrer" aria-label="Instagram sample link" title="Instagram"><Instagram size={17}/></a></div>;}
export function ResumeButton({link=false}:{link?:boolean}) {return link?<a href={profile.resume} download="Alex-Morgan-Sample-Resume.pdf" className="resume-link"><Download size={13}/>Download Resume<ArrowUpRight size={12}/></a>:<Button asChild size="lg"><a href={profile.resume} download="Alex-Morgan-Sample-Resume.pdf"><Download size={15}/>Download Resume</a></Button>;}
export function SampleLink({kind}:{kind:'GitHub'|'Live Demo'}){return <Button variant="link" className="h-auto p-0 text-xs text-muted-foreground" onClick={()=>toast.info(`${kind} is a sample link. A real project URL can be connected later.`)}>{kind==='GitHub'?<Github size={13}/>:<ArrowUpRight size={13}/>} {kind}</Button>;}
